handled align parameters

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,31 +16,17 @@
 # along with abkahzia. If not, see <http://www.gnu.org/licenses/>.
 
 
-# This script configures abkhazia before installation. It does the
-# following:
+# This script configures abkhazia before installation. It checks if
+# dependancies are installed (sox, shorten and CMU dict) and setup the
+# path to kaldi. It also creates the following files in ./abkhazia/share
 #
-# - check if dependancies are installed (sox, shorten and CMU dict)
-#
-# - ask for the path to kaldi
-#
-# - init a default configuration file for abkhazia in abkhazia/share
-#
-# - init path.sh and cmd.sh in abkhazia/share
+# - abkhazia.cfg default configuration file
+# - path.sh and cmd.sh used by kaldi recipes
 #
 # Until all is correctly configured, the script fails with an error
 # message advising you how to fix the issue. Fix it and rerun the
 # script until it succeed.
 
-
-
-function failure {
-    echo "Configuration failed !
-
-$1
-
-Please fix the problem and run this script again";
-    exit 1;
-}
 
 
 # absolute path to the abkhazia setup directory
@@ -49,6 +35,16 @@ setupdir=`readlink -f .`
 # path to the share directory in abkhazia
 share=$setupdir/abkhazia/share
 
+
+# called when a configuration error occurs
+function failure {
+    echo "Configuration failed !
+
+$1
+
+Please fix the problem and run this script again";
+    exit 1;
+}
 
 
 # Download the CMU pronouncing dictionary if not present
@@ -68,6 +64,7 @@ sox=`which sox`
 sox_failure="sox not found on your system, please install it (see http://sox.sourceforge.net)"
 [ ! -z $sox ] && echo "Found sox as $sox" || failure "$sox_failure"
 
+
 # check shorten is installed
 shorten=`which shorten`
 shorten_failure="shorten not found on your system, please install it from
@@ -75,61 +72,15 @@ http://etree.org/shnutils/shorten/dist/src/shorten-3.6.1.tar.gz"
 [ ! -z $shorten ] && echo "Found shorten as $shorten" || failure "$shorten_failure"
 
 
-
 # Configuring abkhazia/share/abkhazia.cfg
 conf=$share/abkhazia.cfg
 if [ ! -e $conf ]; then
     # Init an empty configuration file if not existing
     echo "writing $conf"
-    cat > $conf <<EOF
-# This is the abkhazia configuration file. This file is automatically
-# generated during installation. Change the values in here to overload
-# the default configuration.
-
-[abkhazia]
-# The absolute path to the output data directory of abkhazia.
-data-directory: $setupdir/data
-
-[kaldi]
-# The absolute path to the kaldi distribution directory
-# YOU MUST SPECIFY THIS PATH MANUALLY.
-kaldi-directory:
-
-[corpus]
-# In this section you can specify the default input directory where to
-# read raw data for each supported corpus. By doing so, the
-# <input-dir> argument of 'abkhazia prepare <corpus>' becomes optional
-# for the corpus you have specified directories here.
-aic-directory:
-buckeye-directory:
-csj-directory:
-globalphone-directory:
-librispeech-directory:
-wsj-directory:
-xitsonga-directory:
-
-[split]
-# Defines the default proportion of data for the test set
-default-test-proportion: 0.5
-
-[align]
-# Do all computations if true, else focu on the main ones
-optional-silence: true
-
-# Feature parameters
-use-pitch: true
-
-# Speaker-independent triphone models parameters
-speaker-independent-states: 2500
-speaker-independent-gauss: 15000
-
-# Speaker-adaptive triphone models parameters
-speaker-adaptive-states: 2500
-speaker-adaptive-gauss: 15000
-EOF
+    cp $share/abkhazia.cfg.in $share/abkhazia.cfg
     failure "Please specify the path to the kaldi root directory in $conf"
 else
-    # check kaldi-dircetory is defined in the configuration file if existing
+    # if existing, check kaldi-directory is defined in it
     kaldi=`cat $conf | sed '/^#/d' | grep kaldi-directory | cut -d: -f2 | sed 's/^ *//'`
     [ -z $kaldi ] &&
         failure "Please specify the path to the kaldi root directory in $conf"
@@ -170,9 +121,11 @@ else
     echo "edit and customize it if you want to use qsub"
 fi
 
+# all is good !!
 echo "
 Configuration succeed ! To continue installation please type:
     python setup.py build
-    python setup.py install"
+    python setup.py install
+"
 
 exit 0
